#!/usr/bin/env bash
# Concatenate all migrations in SUPABASE_DATABASE_MIGRATION_ORDER.md order.
# Usage: bash scripts/concat-all-migrations.sh > /tmp/creatix-all-migrations.sql
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT/scripts"

files=(
  001_create_schema.sql
  002_add_encrypted_birthday.sql
  add-onboarding-column.sql
  add-analytics-snapshots-unique-constraint.sql
  004_add_platforms.sql
  add-platform-connections-unique-constraint.sql
  006_create_social_profiles.sql
  create-oauth-states-table.sql
  009-create-notifications-table.sql
  010-create-subscriptions-table.sql
  create-dmca-claims-table.sql
  011-circe-shield-schema-updates.sql
  012_reputation_grok_schema_updates.sql
  013_add_platform_niches.sql
  014_user_api_keys.sql
  015_notifications_platform_avatar.sql
  016_notification_preferences.sql
  017_platform_connections_unique_platform_access_token.sql
  018_divine_manager.sql
  019_divine_intent_log.sql
  019_fan_ai_summaries_housekeeping.sql
  020_profiles_identity_columns.sql
  021_dmca_proofs_storage_bucket.sql
  022_profiles_former_usernames.sql
  023_reputation_mentions_scan_channel.sql
  024_reputation_briefing_profiles.sql
  025_leak_alerts_workflow.sql
  026_profiles_reputation_identity.sql
  027_divine_mimic_profile.sql
  028_fan_thread_insights.sql
  029_reputation_briefing_history.sql
  030_fan_thread_insights_profile.sql
  031_divine_voice_memory.sql
  032_divine_fan_recents.sql
  033_divine_messaging_hub.sql
  034_fan_classification_notifications_platform.sql
  036_content_external_platform.sql
  037_mimic_session.sql
  038_profiles_community_links.sql
  039_community_tips.sql
  040_subscriptions_billing_tiers.sql
  040_fan_thread_scan_automation.sql
  041_fans_crm_webhook.sql
)

echo "-- Generated by scripts/concat-all-migrations.sh — review before running on production."
echo

for f in "${files[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "Missing: $f" >&2
    exit 1
  fi
  echo "-- ========== $f =========="
  cat "$f"
  echo
done
